services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    networks:
           default:
                ipv4_address: $POSTGRESDB_IP #172.18.0.2
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_PORT:$POSTGRESDB_PORT
    volumes:
      - db:/var/lib/postgres
  backend:
    depends_on:
      - postgresdb
    build: ./backend
    #restart: unless-stopped
    env_file: ./.env
    ports:
      - $BACKEND_NODE_PORT:$BACKEND_NODE_PORT
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=$POSTGRESDB_PORT
      - POSTGRESDB_IP=$POSTGRESDB_IP
    stdin_open: false
    tty: true
    #command: "DATABASE_URL=$DATABASE_URL npm run migrate:up"
    networks:
           default:
                ipv4_address: 172.18.0.3
  app:
    depends_on:
      - backend         
    build: ./script_sn_weather
    env_file: ./.env
    #ports:
      #- $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - BACKEND_NODE_IP:$BACKEND_NODE_IP
      - BACKEND_NODE_PORT:$BACKEND_NODE_PORT
      - HOST_API=$HOST_API
      - HOST_WEATHER_API=$HOST_WEATHER_API
      - API_KEY=$API_KEY        
    #stdin_open: false
    tty: true
    networks:
           default:
                ipv4_address: 172.18.0.4
        

volumes: 
  db:
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

