
FROM node:22

WORKDIR /script_sn_weather
COPY package.json .
RUN npm install
COPY . .
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod 777 /usr/local/bin/docker-entrypoint.sh && \
    ln -s usr/local/bin/docker-entrypoint.sh /

ENTRYPOINT ["docker-entrypoint.sh"]
# CMD npm start